class Locators:
    DISPLAY_NAME_LABEL = "Display name"
    HANDLE_NAME_LABEL = "Handle name"
    PASSWORD_LABEL = "Password"
    REGISTER_BUTTON = " Register"
    USERNAME_INPUT = "#UserName"
    PASSWORD_INPUT = "#Password"
    LOGIN_BUTTON = "Login"
    PRIVATE_MESSAGES_TAB = "span:has-text('Private Messages')"
    MESSAGE_INPUT = "input[placeholder='Enter a message...']"
    SEND_MESSAGE_BUTTON = "button.ui.labeled.icon.green.button"